.\" Process this file with
.\" groff -man -Tascii imlib_config.1
.\"
.TH imlib_config 1 "August 1999" "Library Configuration" "User Manuals"
.SH NAME
imlib_config \- Imlib Configuration Editor
.SH SYNOPSIS
.B imlib_config
.SH DESCRIPTION
.B imlib_config
is a program that is used to customize the Imlib library run-time
configuration.  Customizable aspects of Imlib include the color
palette, rendering characterstics, and color correction.

Note that
.B imlib_config
is not the same as the
.B imlib-config
script.
.SH "SEE ALSO"
.BR imlib-config (1)
.SH AUTHOR
Ossama Othman <ossama@debian.org>
