#ifndef GLIBS
#define GLIBS
#include "../include/gfile.h"
#include "../include/gfile.c"
#include "../include/ghttp.h"
#include "../include/ghttp.c"
#include "../include/gplot.h"
#include "../include/gplot.c"
#include "../include/gpost.h"
#include "../include/gpost.c"
#endif GLIBS
