#!/bin/sh
#
# Shamelessly ripped form gtk's gtk-config.in
#

gx_libs=" -ljpeg -ltiff -lgif -lpng -lz -lm"
gdk_gx_libs="  -ljpeg -ltiff -lgif -lpng -lz -lm"
gdk_libs=""

prefix=/usr/local
exec_prefix=${prefix}
exec_prefix_set=no

usage="\
Usage: imlib-config [--prefix[=DIR]] [--exec-prefix[=DIR]] [--version] [--libs] [--libs-gdk] [--cflags] [--cflags-gdk]"

if test $# -eq 0; then
      echo "${usage}" 1>&2
      exit 1
fi

while test $# -gt 0; do
  case "$1" in
  -*=*) optarg=`echo "$1" | sed 's/[-_a-zA-Z0-9]*=//'` ;;
  *) optarg= ;;
  esac

  case $1 in
    --prefix=*)
      prefix=$optarg
      if test $exec_prefix_set = no ; then
        exec_prefix=$optarg
      fi
      ;;
    --prefix)
      echo $prefix
      ;;
    --exec-prefix=*)
      exec_prefix=$optarg
      exec_prefix_set=yes
      ;;
    --exec-prefix)
      echo $exec_prefix
      ;;
    --version)
      echo 1.9.15
      ;;
    --cflags)
      if test ${prefix}/include != /usr/include ; then
        includes=-I${prefix}/include
      fi
      echo $includes  -I/usr/local/include 
      ;;
    --cflags-gdk)
      if test ${prefix}/include != /usr/include ; then
        includes=-I${prefix}/include
      fi
      echo `no --cflags` $includes  -I/usr/local/include
      ;;
    --libs)
      libdirs=-L${exec_prefix}/lib
      echo $libdirs -lImlib  $gx_libs -lXext   -lSM -lICE -lXext -lX11 
      ;;
    --libs-gdk)
      libdirs=-L${exec_prefix}/lib
      echo $libdirs -lgdk_imlib$gdk_gx_libs `no --libs` $gdk_libs
      ;;
    *)
      echo "${usage}" 1>&2
      exit 1
      ;;
  esac
  shift
done

exit 0
